// <auto-generated />
using System;
using Crud.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crud.DataAccess.Migrations
{
    [DbContext(typeof(BeerDbContext))]
    [Migration("20191205181546_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crud.DataAccess.Models.Beer", b =>
                {
                    b.Property<Guid>("BeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeerDescription")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<byte[]>("BeerLabelImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BeerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeerId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            BeerId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            BeerDescription = "Lorem ipsum 1",
                            BeerName = "Żywiec"
                        },
                        new
                        {
                            BeerId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            BeerDescription = "Lorem ipsum 1",
                            BeerName = "Lech"
                        },
                        new
                        {
                            BeerId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            BeerDescription = "Lorem ipsum 1",
                            BeerName = "Okocim"
                        },
                        new
                        {
                            BeerId = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            BeerDescription = "Lorem ipsum 1",
                            BeerName = "Specjal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
